name: telegram
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  convert: ^3.0.0
  crclib:
    git:
      url: git://github.com/google/crclib.dart.git
      ref: nullsafety

  crypto: ^3.0.0
  pointycastle: ^3.3.1

dev_dependencies:
  test: ^1.17.0
